CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_name VARCHAR(255) NOT NULL,
    password VARCHAR(255),

    PRIMARY KEY (id),
    CONSTRAINT uk_users_username UNIQUE (user_name)
);

CREATE TABLE IF NOT EXISTS public."match" (
	match_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	description varchar(255) NULL,
	match_date date NULL,
	match_time time NULL,
	team_a varchar(255) NULL,
	team_b varchar(255) NULL,
	sport int4 NULL,
	CONSTRAINT match_pkey PRIMARY KEY (match_id)
);

CREATE TABLE IF NOT EXISTS public.match_odd (
	match_odd_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	match_id int8 NOT NULL,
	specifier varchar(10) NULL,
	odd float8 NULL,

	CONSTRAINT fk_match_odd_match
            FOREIGN KEY (match_id)
            REFERENCES public."match"(match_id)
            ON DELETE CASCADE

);